services:
  - type: web
    name: sonic-runner-game
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /
    autoDeploy: true 